#!/bin/sh

set -e

REPOSITORY=$(CDPATH=; cd -- "$(dirname -- "$0")/.." && pwd -P)
COMMAND="$1"
: ${JULIA:=julia}

if [ -z "$COMMAND" ]; then
    echo "usage: $(basename "$0") <command> [args...]"
    echo
    echo "commands:"
    for TOOL in $(cd "$REPOSITORY/tools"; echo */run.jl); do
        echo "  ${TOOL%/run.jl}"
    done
    exit 0
fi

TOOL="$REPOSITORY/tools/$COMMAND"

"$JULIA" --project="$TOOL" -- - <<JULIA_VERSION_CHECK
    import Pkg
    REQUIRED = Pkg.Versions.semver_spec(
        Pkg.TOML.parse(read(Pkg.project().path, String))["compat"]["julia"]
    )
    if !(VERSION in REQUIRED)
        @error "Incompatible Julia version" CURRENT=VERSION REQUIRED
        exit(1)
    end
JULIA_VERSION_CHECK

JULIA_VERSION="$("$JULIA" --version)"
JULIA_MAJOR_MINOR="$("$JULIA" -e '
    println("$(VERSION.major).$(VERSION.minor)")
')"
REPOSITORY_VERSION="$(cd "$REPOSITORY"; "$JULIA" -e '
    import LibGit2;
    @__DIR__() |>
    LibGit2.GitRepo |>
    LibGit2.GitDescribeResult |>
    LibGit2.format |>
    print
')"

# Check if `]instantiate` needs to be run for the tool environment's
# `Manifest.toml`. If so, run it and take note of the instantiated repository
# version, Julia version and state (unless the directory is write-protected,
# which is not really a problem since, though adding latency, `]instantiate` is
# idempotent and `]precompile` does not write in this directory). If any of
# these have changed since the last run, we potentially need to reinstantiate
# and recompile.
MANIFEST_FILE="$TOOL/Manifest-v$JULIA_MAJOR_MINOR.toml"
INSTANTIATED_FILE="$TOOL/Instantiated-v$JULIA_MAJOR_MINOR.toml"
INSTANTIATED_WITH_FILE="$TOOL/Instantiated-v${JULIA_MAJOR_MINOR}-from.version"
INSTANTIATED_WITH="$(cat "$INSTANTIATED_WITH_FILE" 2>/dev/null || true)"
if
    [ "$REPOSITORY_VERSION, $JULIA_VERSION" != "$INSTANTIATED_WITH" ] || \
    ! cmp --silent "$MANIFEST_FILE" "$INSTANTIATED_FILE"
then
    >&2 echo \
        "Info: '$COMMAND' Julia environment may be stale," \
        "running \`]instantiate\`..."
    if [ "$COMMAND" = inspect ]; then
        >&2 echo \
            "Info: Empty windows may open briefly during precompilation;" \
            "do not close them manually."
    fi

    (
        set -x
        env JULIA_PKG_PRECOMPILE_AUTO=0 "$JULIA" --project="$TOOL" \
            -e 'import Pkg; Pkg.instantiate(verbose = true)'
        "$JULIA" --project="$TOOL" \
            -e "import Pkg; Pkg.precompile(strict = true, timing = true)"
    )
    echo "...done."
    if [ -e "$TOOL/Manifest.toml" ]; then
        >&2 echo "Warning: unsupported Julia version '$JULIA_MAJOR_MINOR'."
    fi
    cp "$MANIFEST_FILE" "$INSTANTIATED_FILE" 2>/dev/null || true
    echo "$REPOSITORY_VERSION, $JULIA_VERSION" \
        >"$INSTANTIATED_WITH_FILE" || true
fi

shift

exec env JULIA_PKG_PRECOMPILE_AUTO=0 \
    "$JULIA" --project="$TOOL" "$TOOL/run.jl" "$@"
